#!/bin/sh

# apt-get install --assume-yes gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools

serverurl='rtmp://live-arn.twitch.tv/app/'$TWITCH_AUTH


GST_DEBUG="--gst-debug=flvmux:0,rtmpsink:0"

SENSOR_ID=0 # 0 for CAM0 and 1 for CAM1 ports
FRAMERATE=30 # Framerate can go from 2 to 60 for 1920x1080 mode
gst-launch-1.0 \
	-v $GST_DEBUG \
	-e nvarguscamerasrc sensor-id=$SENSOR_ID \
	! "video/x-raw(memory:NVMM),width=4032,height=3040,framerate=$FRAMERATE/1" \
	! nvvidconv flip-method=2 \
       	! nvv4l2h264enc  \
	! h264parse  \
        ! flvmux streamable=true name=mux \
        ! rtmpsink location=$serverurl \
